version: "3.8"

services:
  app:
    build:
      context: .
      target: dev
    env_file: .env
    command: sh -c "npm run prisma:migrate:save && npm run prisma:seed:run && npm run start:dev"
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:14.0-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: investments_service
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
       - postgres:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d investments_service"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
    postgres:
